### ISSUE TITLE
${ trial_court.address.on_one_line() } -- need to add the leading zero to the court zip codes; they are cut off

### ISSUE THREAD

**Issue by VTskier** [LSVermont/docassemble-VTSharedYMLFile#9]
This info is pulled from our courts_list Excel file in SharedYMLFile.

![image](https://github.com/LSVermont/docassemble-VTDivorce/assets/104463248/2d3e12b1-7ddb-42f0-9d9c-e3f875605129)

**Comment by miabonardi** [comment]
Transfered this issue from VTDivorce to VTSharedYMLFile where the court list xlsx lives

**Comment by nonprofittechy** [comment]
Tested; this seems to be fixed by https://github.com/SuffolkLITLab/docassemble-AssemblyLine/pull/841

**Comment by nonprofittechy** [comment]
I've installed the court-enhancements branch on your server
